# .goreleaser.yml
# Build customization
builds:
  - main: ./
    binary: ir_decoder
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
